# About: Base CD pipeline to deploy application's helm chart into the private EKS (kubernetes) cluster using the gitops approach through argocd.
name: CD pipeline - argocd
permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        type: string
    secrets:
      GHA_RUNNER_POC_CICD_PAT:
        required: true

env:
  APPLICATION: ${{ vars.APPLICATION }}
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}
  SECRETMANAGER_SECRET_ID: eks-infra/${{ vars.ENVIRONMENT }}/${{ vars.APPLICATION }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  ARGOCD_APPLICATIONS_REPO: argocd-application-test

jobs:
  deploy:
    runs-on: github-arc-runner-set
    environment: ${{ inputs.environment }} # when set, automatically access caller's workflow environments variables
    steps:
    - name: generate env vars
      run: |
        BUILD_DATE=$(date -u +"%Y-%m-%dT%H.%M.%SZ")
        echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
        echo "DOCKER_TAG=${{ env.ENVIRONMENT }}-$BUILD_DATE" >> $GITHUB_ENV
      shell: bash
    - name: Checkout sourcecode
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::127923327338:role/github-actions-runner-role
        aws-region: us-east-1
        audience: sts.amazonaws.com
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Tag SecretManager
      shell: bash
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install
        aws secretsmanager update-secret-version-stage --secret-id ${{ env.SECRETMANAGER_SECRET_ID }} --version-stage ${{ env.BUILD_DATE }} --move-to-version-id $(aws secretsmanager get-secret-value --secret-id ${{ env.SECRETMANAGER_SECRET_ID }} --version-stage AWSCURRENT | jq .VersionId -r)
    - name: Setup buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          network=host
    - name: Docker build/push
      uses: docker/build-push-action@v5
      env:
        DOCKER_IMAGE: "${{ steps.login-ecr.outputs.registry }}/${{ env.APPLICATION }}:${{ env.DOCKER_TAG }}"
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}
    - name: Checkout application repository
      uses: actions/checkout@v4
      with:
        repository: ricardofukuda-org/${{ env.ARGOCD_APPLICATIONS_REPO }} # Specify the other repo (owner/repo format)
        ref: main
        path: ${{ env.ARGOCD_APPLICATIONS_REPO }} # Clones to $GITHUB_WORKSPACE/other-repo
        token: ${{ secrets.GHA_RUNNER_POC_CICD_PAT }}
    - name: Update ArgoCD application
      # Update and commit the docker tag and values*.yaml files into the git repository 'argocd-application-test' resposible to centralize ArgoCD Application's definition and helm chart live synchronization.
      env:
        ARGOCD_APPLICATION_VALUES_PATH: "applications/overlays/${{ env.ENVIRONMENT }}/${{ env.APPLICATION }}"
      run: |
        cp helm-chart/values.yaml helm-chart/values-${{ env.ENVIRONMENT }}.yaml ${{ env.ARGOCD_APPLICATIONS_REPO }}/${{ env.ARGOCD_APPLICATION_VALUES_PATH }}/

        cd ${{ env.ARGOCD_APPLICATIONS_REPO }}/
        sed -i 's/\(tag: [^\n]\+\)/tag: ${{ env.DOCKER_TAG }} # deploy: ${{ github.actor }} branch: ${{ env.BRANCH_NAME }} commit: ${{ github.sha }}/g' ${{ env.ARGOCD_APPLICATION_VALUES_PATH }}/values-${{ env.ENVIRONMENT }}.yaml
        sed -i 's/\(secret_version: [^\n]\+\)/secret_version: ${{ env.DOCKER_TAG }} # ${{ env.SECRETMANAGER_SECRET_ID }}/g' ${{ env.ARGOCD_APPLICATION_VALUES_PATH }}/values-${{ env.ENVIRONMENT }}.yaml
        
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add ${{ env.ARGOCD_APPLICATION_VALUES_PATH }}/
        git commit -m "${{ env.APPLICATION }}/${{ env.DOCKER_TAG }} deploy"
        git push
